name: "chrony"
services:
  chrony:
    image: "11notes/chrony:4.6.1"
    container_name: "chrony"
    environment:
      TZ: "Europe/Zurich"
    ports:
      - "123:123/udp"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=123
    restart: "always"